import express from "express";
import nodemailer from "nodemailer";

const router = express.Router();

router.post("/contact", async (req, res) => {
  const { name, email, subject, number, message } = req.body;

  try {
    const transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS,
      },
    });

    const mailOptions = {
      from: email,
      to: process.env.EMAIL_USER,
      subject,
      html: `
    <div style="margin:0; padding:0; background-color:#f4f6f8; font-family:'Helvetica Neue', Arial, sans-serif;">
      <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" 
        style="max-width:600px; margin:40px auto; background-color:#ffffff; border-radius:8px; 
        box-shadow:0 2px 10px rgba(0,0,0,0.05); overflow:hidden;">
        
        <tr>
          <td style="background-color:#0d47a1; padding:24px 0; text-align:center;">
            <img src="/icon_logo.png" alt="IMTC Payments" width="150" 
              style="display:block; margin:0 auto;"/>
            <h1 style="color:#ffffff; font-size:22px; font-weight:600; margin:10px 0 0;">
              New Contact Form Submission
            </h1>
          </td>
        </tr>

        <tr>
          <td style="padding:30px;">
            <p style="font-size:15px; color:#333333; line-height:1.6;">
              You’ve received a new message from the IMTC Payments website contact form. 
              Here are the details:
            </p>

             <div style="background-color:#f8fafc; border:1px solid #e2e8f0; 
              border-radius:6px; padding:15px; margin:15px 0;">
              <p style="margin:0; font-size:15px; color:#111827;">
                <strong>Name:</strong> ${name} <br/>
                <strong>Email:</strong> ${email} <br/>
                <strong>Phone Number:</strong> ${number} <br/>
              </p>
            </div>

            <div style="margin-top:20px;">
              <p style="font-size:15px; color:#333333; margin-bottom:8px;"><strong>Message:</strong></p>
              <p style="font-size:15px; color:#444444; line-height:1.6; background-color:#f9fafb; 
                border:1px solid #e5e7eb; padding:15px; border-radius:6px;">
                ${message}
              </p>
            </div>

            <p style="font-size:14px; color:#666666; margin-top:25px;">
              This email was automatically generated by the IMTC Payments contact form system.
            </p>

            <p style="font-size:15px; color:#333333; margin-top:30px;">
              Best Regards,<br/>
              <strong>IMTC Payments Website</strong>
            </p>
          </td>
        </tr>

        <tr>
          <td style="background-color:#f1f5f9; text-align:center; padding:15px;">
            <p style="margin:0; font-size:12px; color:#6b7280;">
              © ${new Date().getFullYear()} IMTC Payment Solutions LLP. All rights reserved.<br/>
              <a href="https://imtcpayments.com" style="color:#0d47a1; text-decoration:none;">
                imtcpayments.com
              </a>
            </p>
          </td>
        </tr>
      </table>
    </div>
  `,
    };

    await transporter.sendMail(mailOptions);
    res
      .status(200)
      .json({ message: "Your message has been sent successfully!" });
  } catch (error) {
    console.error(error);
    res
      .status(500)
      .json({ message: "Failed to send message. Try again later." });
  }
});

export default router;
